# Ansible playbook to setup dot files via linking, source'ing or includes
# 
# Usage: ansible-playbook -i hosts ansible-dotfiles.yml
#

---
- hosts: localhost
  vars:
    is_server: "{{ ansible_distribution == 'Ubuntu' }}"
    
  tasks:
    - name: Checkout this repo in home/.personalconfig
      git: repo=git://github.com/sharjeel/dotfiles.git dest=~/.personalconfig update=no

    - name: Setup personal emacs configuration
      lineinfile: dest={{ ansible_env.HOME }}/.emacs.d/init.el state=present create=yes insertbefore='BOF'
                  regexp='\(load-file \(expand-file-name ".*"\)\); Customized config'
                  line='(load-file (expand-file-name "{{ item }}")); Customized config'
      with_items:
         - "{{ ansible_env.HOME }}/.personalconfig/emacs.init.el"

    - name: Setup personal bashmarks
      lineinfile: dest={{ ansible_env.HOME }}/.sdirs state=present create=yes insertafter='EOF'
                  regexp='^source ' line="source {{ item }}"
      with_items:
         - "{{ ansible_env.HOME }}/.personalconfig/bashmarks.sdirs"

    - name: Setup personal zshrc
      lineinfile: dest={{ ansible_env.HOME }}/.zshrc state=present create=yes insertafter='source.*oh-my-zsh\.sh'
                  regexp='^source.*zsh.zshrc' line="source {{ item }}"
      with_items:
          - "{{ ansible_env.HOME }}/.personalconfig/zsh.zshrc"

    - name: Link oh-my-zsh theme
      file: state=link src={{ ansible_env.HOME }}/.personalconfig/sharjeel.zsh-theme dest={{ ansible_env.HOME }}/.oh-my-zsh/themes/sharjeel.zsh-theme

    - name: Set theme
      lineinfile: dest={{ ansible_env.HOME }}/.zshrc state=present create=yes insertafter='source.*oh-my-zsh\.sh'
                  regexp='^ZSH_THEME=' line='ZSH_THEME="sharjeel"'

    - name: Link tmux config
      file: state=link src={{ ansible_env.HOME }}/.personalconfig/tmux.conf dest={{ ansible_env.HOME }}/.tmux.conf



