# Ansible playbook to setup dot files via linking, source'ing or includes
# 
# Usage: ansible-playbook -i hosts ansible-dotfiles.yml
#

---
- hosts: localhost
  vars:
    is_server: "{{ ansible_distribution == 'Ubuntu' }}"
    
  tasks:
    - name: Checkout this repo in home/.personalconfig
      git: repo=git://github.com/sharjeel/dotfiles.git dest=~/.personalconfig update=no

    - shell: echo $HOME
      register: userhome

    - name: Setup personal emacs configuration
      lineinfile: dest={{ userhome.stdout }}/.emacs.d/init.el state=present create=yes insertbefore='BOF'
                  regexp='\(load-file \(expand-file-name ".*"\)\); Customized config'
                  line='(load-file (expand-file-name "{{ item }}")); Customized config'
      with_items:
         userhome.stdout + '/.personalconfig/emacs.init.el'

    - name: Setup personal bashmarks
      lineinfile: dest={{ userhome.stdout }}/.sdirs state=present create=yes insertafter='EOF' create=yes
                  regexp='^source ' line="source {{ item }}"
      with_items:
         userhome.stdout + '/.personalconfig/bashmarks.sdirs'

    - name: Setup personal zshrc
      lineinfile: dest={{ userhome.stdout }}/.zshrc state=present create=yes insertbefore='source.*oh-my-zsh\.sh'
                  regexp='^source.*zsh.zshrc' line="source {{ item }}"
      with_items:
          userhome.stdout + '/.personalconfig/zsh.zshrc'

    - name: Set prompt color for ubuntu servers
      lineinfile: dest={{ item }} state=present create=yes insertafter='source.*oh-my-zsh\.sh'
                 regexp='PS1=.*' line='PS1="%B%{$fg[red]%}%n@%{$fg[green]%}%m %{$fg[blue]%}%~ $ %{$reset_color%}% "'
      when: is_server
      with_items:
          userhome.stdout + '/.zshrc'
